export const addettiList: string[] = [
  "639 ABBATE EMANUELE",
  "2 GRASSO DAVIDE",
  "14 BALISTRERI GIOVANNI",
  "25 CARUSO GIUSEPPE",
  "30 DI GAETANO MARIO",
  "45 FANARA ANTONIO",
  "50 GAMBINO LUCA",
  "60 GUASTELLA MARCO",
  "75 MESSINA ANDREA",
  "80 MINARDI PAOLO",
  "90 PALMERI FRANCESCO",
  "100 RAFFAELE GIUSEPPE",
];

export const servizioOptions: string[] = [
  "Guardia Particolare Giurata",
  "Addetto Servizi Fiduciari",
  "Addetto Servizi Fiduciari con Auto",
  "Servizio di Piantonamento",
  "Servizio di Ronda",
  "Servizio di Scorta Valori",
  "Servizio di Vigilanza Armata",
  "Servizio di Portierato",
];

export const tipologiaAutomezzoOptions: string[] = [
  "Autocarro",
  "Autogru",
  "Betoniera",
  "Betonpompa",
  "Bulldozer",
  "Camion",
  "Carrello elevatore",
  "Dumper",
  "Escavatore",
  "Fresatrice stradale",
  "Furgone",
  "Gru a torre",
  "Gru cingolata",
  "Pala caricatrice",
  "Perforatrice",
  "Piastre vibranti",
  "Piattaforma aerea",
  "Rullo compressore",
  "Spazzatrice",
  "Trattore",
  "Vibrofinitrice",
];

export const marcaAutomezzoOptions: string[] = [
  "Bell",
  "Bobcat",
  "Caterpillar (CAT)",
  "CIFA",
  "DAF",
  "Doosan",
  "Hitachi",
  "Iveco",
  "JCB",
  "Komatsu",
  "Kubota",
  "Liebherr",
  "MAN",
  "Manitowoc",
  "Mercedes-Benz",
  "Palfinger",
  "Putzmeister",
  "SANY",
  "Scania",
  "Schwing",
  "Terex",
  "Terex Trucks",
  "Volvo Construction Equipment",
  "Volvo Trucks",
  "Wacker Neuson",
];

export const tipologiaAttrezzoOptions: string[] = [
  "Avvitatore",
  "Cavalletto",
  "Cinghie di sollevamento",
  "Distanzaometro laser",
  "Leve di sollevamento",
  "Levigatrice",
  "Livella laser",
  "Martello demolitore",
  "Pistola termica",
  "Ponteggio (attrezzatura modulare)",
  "Saldatrice",
  "Scala",
  "Sega circolare",
  "Seghetto alternativo",
  "Smerigliatrice angolare (flessibile)",
  "Tracciatore a gesso",
  "Trapano",
];

export const marcaAttrezzoOptions: string[] = [
  "Altrad",
  "Bahco",
  "Black+Decker",
  "Bosch",
  "Crosby",
  "DeWalt",
  "Doka",
  "ESAB",
  "Facom",
  "Faraone",
  "Fervi",
  "Festool",
  "Fronius",
  "Gedore",
  "Gunnebo",
  "Hailo",
  "Hilti",
  "Hitachi",
  "Irwin",
  "Keson",
  "Krause",
  "Layher",
  "Leica",
  "Lincoln Electric",
  "Makita",
  "Metabo",
  "Miller",
  "Milwaukee",
  "Peri",
  "Proto",
  "RUD",
  "Ryobi",
  "Scafom-rux",
  "SpanSet",
  "Stanley",
  "Steinel",
  "Svelt",
  "Tajima",
  "Telwin",
  "Topcon",
  "Wagner",
  "Wolfcraft",
  "Yale",
  "Zarges",
];