// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://abzjbnvrshimsegaltlq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFiempibnZyc2hpbXNlZ2FsdGxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MDk5NjMsImV4cCI6MjA2NjE4NTk2M30.DjCcqrhSi6kSp1ODAAKFLzJLvYPm5jYlZAdE-FL2fEU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);